/**
 * CreateBoardDialog Component
 *
 * Dialog for creating a new Kanban board.
 * Allows user to enter name and optionally select a template for initial lists.
 */

import { useState } from 'react';
import { DEFAULT_BOARD_TEMPLATES } from '../../types/issueBoard';
import './CreateBoardDialog.css';

/**
 * @param {Object} props
 * @param {boolean} props.isOpen - Whether dialog is visible
 * @param {function} props.onClose - Callback to close dialog
 * @param {function} props.onCreate - Callback when board is created (boardData) => void
 * @param {boolean} props.saving - Whether a save operation is in progress
 */
export function CreateBoardDialog({ isOpen, onClose, onCreate, saving = false }) {
  const [name, setName] = useState('');
  const [template, setTemplate] = useState('kanban'); // 'empty' | 'kanban' | 'bugTriage'
  const [error, setError] = useState('');

  if (!isOpen) return null;

  const handleSubmit = (e) => {
    e.preventDefault();

    // Validate
    const trimmedName = name.trim();
    if (!trimmedName) {
      setError('Please enter a board name');
      return;
    }

    // Get lists from template
    let lists = [];
    if (template !== 'empty' && DEFAULT_BOARD_TEMPLATES[template]) {
      lists = DEFAULT_BOARD_TEMPLATES[template].lists.map((list) => ({
        ...list,
        id: '', // Will be generated by the hook
      }));
    }

    // Create board data
    const boardData = {
      name: trimmedName,
      lists,
      showOthers: true,
      showClosed: true,
    };

    onCreate(boardData);
  };

  const handleClose = () => {
    setName('');
    setTemplate('kanban');
    setError('');
    onClose();
  };

  return (
    <div className="create-board-overlay" onClick={handleClose}>
      <div
        className="create-board-dialog"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="create-board-header">
          <h3>Create New Board</h3>
          <button
            className="create-board-close modal-close-btn"
            onClick={handleClose}
            disabled={saving}
          >
            <i className="fas fa-times" />
          </button>
        </div>

        {/* Content */}
        <form onSubmit={handleSubmit}>
          <div className="create-board-content">
            {/* Name input */}
            <div className="create-board-field">
              <label htmlFor="board-name">Name</label>
              <input
                id="board-name"
                type="text"
                value={name}
                onChange={(e) => {
                  setName(e.target.value);
                  setError('');
                }}
                placeholder="Enter board name..."
                className={error ? 'error' : ''}
                disabled={saving}
                autoFocus
              />
              {error && <span className="create-board-error">{error}</span>}
            </div>

            {/* Template selection */}
            <div className="create-board-field">
              <label>Initial Lists</label>
              <div className="create-board-templates">
                <label className="create-board-template">
                  <input
                    type="radio"
                    name="template"
                    value="empty"
                    checked={template === 'empty'}
                    onChange={(e) => setTemplate(e.target.value)}
                    disabled={saving}
                  />
                  <span className="template-label">Empty</span>
                  <span className="template-description">
                    Start with no lists (add later)
                  </span>
                </label>

                <label className="create-board-template">
                  <input
                    type="radio"
                    name="template"
                    value="kanban"
                    checked={template === 'kanban'}
                    onChange={(e) => setTemplate(e.target.value)}
                    disabled={saving}
                  />
                  <span className="template-label">To Do / In Progress / Done</span>
                  <span className="template-description">
                    Standard Kanban workflow with State labels
                  </span>
                </label>

                <label className="create-board-template">
                  <input
                    type="radio"
                    name="template"
                    value="bugTriage"
                    checked={template === 'bugTriage'}
                    onChange={(e) => setTemplate(e.target.value)}
                    disabled={saving}
                  />
                  <span className="template-label">Bug Triage</span>
                  <span className="template-description">
                    New / Confirmed / In Progress for bug tracking
                  </span>
                </label>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="create-board-footer">
            <button
              type="button"
              className="create-board-btn create-board-btn-cancel"
              onClick={handleClose}
              disabled={saving}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="create-board-btn create-board-btn-create"
              disabled={saving}
            >
              {saving ? (
                <>
                  <i className="fas fa-spinner fa-spin" />
                  Creating...
                </>
              ) : (
                'Create Board'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
